# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15gNmXBoN4DhqRZms911rX-kTXhBHlX0D
"""

# Módulos necesarios
from datetime import datetime
from data_models import USUARIOS, RESERVAS, ASIENTOS, CARTELERA, TARIFAS
from validation_utils import validar_documento, validar_nombre, print_errores
from file_manager import exportar_csv_reservas, exportar_csv_usuarios
from report_generator import imprimir_mapa_asientos, generar_reportes, imprimir_reportes, imprimir_usuarios, consultar_funciones_cartelera

# --- Funciones de Actividades del Menú Principal ---

def registrar_usuario():
    """Permite registrar un nuevo usuario con validaciones."""
    print("\n[Registro de Usuario] Paso a paso")

    # 1. Solicitar y validar Documento
    while True:
        documento = input("Ingresa tu documento de identidad: ").strip()
        doc_err = validar_documento(documento)
        if doc_err:
            print_errores(doc_err)
            continue
        if documento in USUARIOS:
            print("\n⚠️ Este documento ya está registrado. Volviendo al menú principal.")
            return
        break

    # 2. Solicitar y validar Nombre y Apellido
    while True:
        nombre = input("Ingresa tu nombre: ").strip().title()
        apellido = input("Ingresa tu apellido: ").strip().title()

        nombre_err = validar_nombre(nombre)
        apellido_err = validar_nombre(apellido)

        if nombre_err or apellido_err:
            print_errores([f"Nombre: {e}" for e in nombre_err] + [f"Apellido: {e}" for e in apellido_err])
            continue
        break

    # 3. Seleccionar Tipo de Vínculo
    while True:
        print("\nTipos de vínculo disponibles:")
        for key, data in TARIFAS.items():
            print(f"  {key}. {data['vinculo']} - ${data['valor']:,}")

        try:
            opcion_vinculo = int(input("Selecciona el número de tu tipo de vínculo: "))
            if opcion_vinculo in TARIFAS:
                datos_vinculo = TARIFAS[opcion_vinculo]
                break
            else:
                print("Opción de vínculo inválida. Intenta de nuevo.")
        except ValueError:
            print("Entrada inválida. Debe ser un número.")

    # 4. Registrar y Exportar
    USUARIOS[documento] = {
        "nombre": nombre,
        "apellido": apellido,
        "vinculo": datos_vinculo["vinculo"],
        "valor": datos_vinculo["valor"]
    }

    print(f"\n🎉 ¡Usuario {nombre} registrado con éxito como {datos_vinculo['vinculo']}! Tarifa: ${datos_vinculo['valor']:,}")
    exportar_csv_usuarios()

def seleccionar_funcion():
    """Muestra la cartelera y permite seleccionar una función."""
    print("\n--- Cartelera de Funciones ---")
    funciones_disponibles = []

    for i, f in enumerate(CARTELERA):
        mapa = ASIENTOS.get(i, {})
        disponibles = sum(1 for estado in mapa.values() if estado == 'O')

        if disponibles > 0:
            funciones_disponibles.append(i)
            print(f"[{i+1}] {f['dia']} {f['hora']} - {f['nombre']} | Asientos Disponibles: {disponibles}")

    if not funciones_disponibles:
        print("⚠️ Lo sentimos, no hay funciones disponibles en este momento.")
        return None

    while True:
        try:
            opcion = int(input("\nSelecciona el número de la función: "))
            idx_funcion = opcion - 1
            if idx_funcion in funciones_disponibles:
                return idx_funcion
            else:
                print("Opción de función inválida o sin asientos disponibles. Intenta de nuevo.")
        except ValueError:
            print("Entrada inválida. Debe ser un número.")

def solicitar_asiento(idx_funcion):
    """Permite al usuario seleccionar un asiento disponible."""
    imprimir_mapa_asientos(idx_funcion, ASIENTOS)
    mapa = ASIENTOS[idx_funcion]

    while True:
        asiento = input("Ingresa el asiento que deseas reservar (Ej: A1, B10, K11): ").strip().upper()

        if asiento not in mapa:
            print("Asiento inválido. Debe ser una combinación de Fila(A-K) y Columna(1-11).")
        elif mapa[asiento] == 'X':
            print("Ese asiento ya está ocupado. Selecciona uno marcado con 'O'.")
        else:
            return asiento

def confirmar_compra(documento, idx_funcion, asiento):
    """Finaliza el proceso de reserva y genera la factura."""
    datos_usuario = USUARIOS[documento]
    funcion = CARTELERA[idx_funcion]
    valor = datos_usuario["valor"]

    # 1. Registrar Reserva
    RESERVAS.append({
        "documento": documento,
        "idx_funcion": idx_funcion,
        "asiento": asiento,
        "valor": valor,
        "fecha_reserva": datetime.now().strftime("%Y-%m-%d")
    })

    # 2. Ocupar Asiento
    ASIENTOS[idx_funcion][asiento] = 'X'

    # 3. Generar Factura
    print("\n" + "="*40)
    print("        [FACTURA DE COMPRA]")
    print("="*40)
    print(f"USUARIO: {datos_usuario['nombre']} {datos_usuario['apellido']}")
    print(f"DOCUMENTO: {documento}")
    print("-" * 40)
    print(f"FUNCIÓN: {funcion['nombre']}")
    print(f"DÍA/HORA: {funcion['dia']} {funcion['hora']}")
    print(f"ASIENTO: {asiento}")
    print(f"VÍNCULO: {datos_usuario['vinculo']}")
    print("-" * 40)
    print(f"VALOR PAGADO: ${valor:,}")
    print("="*40)

    exportar_csv_reservas()
    print("\n✅ ¡Reserva registrada con éxito!")

def registrar_reserva():
    """Flujo completo para registrar una reserva."""
    documento = input("\nIngresa tu documento de identidad para reservar: ").strip()

    doc_err = validar_documento(documento)
    if doc_err:
        print_errores(doc_err)
        return

    if documento not in USUARIOS:
        print("\n⚠️ No estás registrado. Por favor, regístrate primero (Opción 1).")
        return

    idx_funcion = seleccionar_funcion()
    if idx_funcion is None:
        return

    asiento = solicitar_asiento(idx_funcion)

    if asiento:
        confirmar_compra(documento, idx_funcion, asiento)

def cancelar_reserva(documento):
    """Permite al usuario cancelar una de sus reservas activas."""
    reservas_usuario = [r for r in RESERVAS if r["documento"] == documento]

    if not reservas_usuario:
        print("\n⚠️ No tienes reservas activas. Volviendo al menú principal.")
        return

    print("\n--- Tus Reservas Activas ---")
    for i, r in enumerate(reservas_usuario):
        f = CARTELERA[r["idx_funcion"]]
        print(f"[{i+1}] {f['nombre']} - {f['dia']} {f['hora']} - Asiento: {r['asiento']}")

    while True:
        try:
            opcion = input("Ingresa el número de la reserva a cancelar o '0' para salir: ").strip()

            if opcion == '0':
                print("Cancelación anulada.")
                return

            idx_cancelar = int(opcion) - 1

            if 0 <= idx_cancelar < len(reservas_usuario):
                reserva_a_cancelar = reservas_usuario[idx_cancelar]

                # 1. Liberar Asiento
                idx_funcion = reserva_a_cancelar["idx_funcion"]
                asiento = reserva_a_cancelar["asiento"]
                ASIENTOS[idx_funcion][asiento] = 'O'

                # 2. Eliminar del registro global (se busca y elimina la primera coincidencia)
                RESERVAS.remove(reserva_a_cancelar)

                print(f"\n🗑️ Reserva de {reserva_a_cancelar['asiento']} en {CARTELERA[idx_funcion]['nombre']} cancelada con éxito. Asiento liberado.")
                exportar_csv_reservas()
                break
            else:
                print("Opción inválida. Intenta de nuevo.")
        except ValueError:
            print("Entrada inválida. Debe ser un número.")

def menu_administrador():
    """Menú de opciones para el administrador."""
    while True:
        print("\n--- MENÚ ADMINISTRADOR ---")
        print("1. Consultar Reportes (1, 2, 3, 4, 6)")
        print("5. Lista de usuarios registrados")
        print("7. Exportar CSV (usuarios y reservas)")
        print("8. Volver al Menú Principal")

        op = input("Selecciona una opción: ").strip()

        if op == '1':
            total_reservas, total_recaudo, promedio_diario, usuario_max, usuario_min = generar_reportes()
            imprimir_reportes(total_reservas, total_recaudo, promedio_diario, usuario_max, usuario_min)
        elif op == '5':
            imprimir_usuarios(USUARIOS)
        elif op == '7':
            exportar_csv_usuarios()
            exportar_csv_reservas()
        elif op == '8':
            break
        else:
            print("Opción inválida. Intenta de nuevo.")

def admin_login():
    """Protege el acceso al menú de administrador."""
    admins = {"admin": "admin123", "po_udea": "cinema2025"}

    usuario = input("Usuario Admin: ").strip()
    password = input("Contraseña Admin: ").strip()

    if usuario in admins and admins[usuario] == password:
        print("\n🔑 Acceso de administrador concedido.")
        menu_administrador()
    else:
        print("\n❌ Credenciales inválidas. Acceso denegado.")