# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15gNmXBoN4DhqRZms911rX-kTXhBHlX0D
"""

# Módulos necesarios
# Importar desde el módulo de lógica central
from core_logic import (
    registrar_usuario,
    registrar_reserva,
    cancelar_reserva,
    admin_login,
    consultar_funciones_cartelera
)
# Importar elementos de validación y datos necesarios para el menú
from validation_utils import validar_documento, print_errores
from data_models import USUARIOS, ASIENTOS

def menu_principal():
    """Muestra el menú principal y maneja la interacción del usuario."""
    while True:
        print("\n" + "="*40)
        print("        CINEMA UDEA")
        print("="*40)
        print("1. Registrar Usuario")
        print("2. Registrar Reserva")
        print("3. Cancelar Reserva")
        print("4. Consultar Funciones Fin de Semana")
        print("5. Administrador")
        print("6. Salir")
        print("="*40)

        op = input("Selecciona una opción: ").strip()

        if op == "1":
            registrar_usuario()
        elif op == "2":
            registrar_reserva()
        elif op == "3":
            # Requiere validación de documento en este nivel
            documento = input("Ingresa tu documento para cancelar: ").strip()
            doc_err = validar_documento(documento)
            if doc_err:
                print_errores(doc_err)
            elif documento not in USUARIOS:
                print("\n⚠️ No estás registrado. Regístrate antes de cancelar.")
            else:
                cancelar_reserva(documento)
        elif op == "4":
            consultar_funciones_cartelera(ASIENTOS) # Pasa ASIENTOS como argumento
        elif op == "5":
            admin_login()
        elif op == "6":
            print("\nGracias por usar Cinema UdeA. Hasta pronto.")
            break
        else:
            print("Opción inválida. Intenta de nuevo.")

if __name__ == "__main__":
    menu_principal()
