# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15gNmXBoN4DhqRZms911rX-kTXhBHlX0D
"""

# Módulos necesarios
from datetime import datetime
from src. data_models import USUARIOS, RESERVAS, CARTELERA
# Importamos solo lo necesario de data_models para el reporte

def imprimir_mapa_asientos(idx_funcion, asientos_map):
    """Imprime el mapa de asientos para una función específica."""
    mapa = asientos_map[idx_funcion]
    filas = [chr(i) for i in range(ord('A'), ord('K') + 1)]

    print("\n    " + " ".join([str(i).center(2) for i in range(1, 12)]))
    print("  " + "-" * 33)

    for fila in filas:
        linea = f"{fila} |"
        for col in range(1, 12):
            asiento_id = fila + str(col)
            linea += f" {mapa[asiento_id].center(1)} "
        print(linea)


def generar_reportes():
    """Calcula y devuelve los reportes estadísticos clave."""

    # 1 y 2. Total de reservas y tiquetes
    total_reservas = len(RESERVAS)

    # 3. Total pago realizado
    total_recaudo = sum(r["valor"] for r in RESERVAS)

    # 4. Promedio por venta diario
    promedio_diario = 0
    if RESERVAS:
        ventas_por_dia = {}
        for r in RESERVAS:
            fecha = r.get("fecha_reserva", datetime.now().strftime("%Y-%m-%d"))
            ventas_por_dia[fecha] = ventas_por_dia.get(fecha, 0) + r["valor"]

        if ventas_por_dia:
            promedio_diario = sum(ventas_por_dia.values()) / len(ventas_por_dia)

    # 6. Usuario con mayor y menor cantidad de reservas
    conteo_reservas = {}
    for r in RESERVAS:
        conteo_reservas[r["documento"]] = conteo_reservas.get(r["documento"], 0) + 1

    usuario_max = None
    usuario_min = None

    if conteo_reservas:
        doc_max = max(conteo_reservas, key=conteo_reservas.get)
        doc_min = min(conteo_reservas, key=conteo_reservas.get)

        usuario_max = f"{USUARIOS[doc_max]['nombre']} ({doc_max}) con {conteo_reservas[doc_max]} reservas"
        usuario_min = f"{USUARIOS[doc_min]['nombre']} ({doc_min}) con {conteo_reservas[doc_min]} reservas"

    return total_reservas, total_recaudo, promedio_diario, usuario_max, usuario_min

def imprimir_reportes(total_reservas, total_recaudo, promedio_diario, usuario_max, usuario_min):
    """Imprime los reportes generados."""

    print("\n--- REPORTES ESTADÍSTICOS ---")
    print(f"1. Total de Reservas Registradas: {total_reservas}")
    print(f"2. Total de Tiquetes Vendidos: {total_reservas}")
    print(f"3. Total Pago Realizado (Recaudo): ${total_recaudo:,}")
    print(f"4. Promedio por Venta Diario: ${promedio_diario:,.2f}")

    print("\n--- RANKING DE RESERVAS ---")
    if usuario_max:
        print(f"6. Usuario con Mayor Cantidad de Reservas: {usuario_max}")
        print(f"6. Usuario con Menor Cantidad de Reservas: {usuario_min}")
    else:
        print("No hay reservas registradas para generar ranking.")
    print("-" * 40)

def imprimir_usuarios(usuarios_map):
    """Imprime la lista de usuarios (Reporte 5)."""
    print("\n👥 --- LISTA DE USUARIOS REGISTRADOS ---")
    for doc, data in usuarios_map.items():
        print(f"DOC: {doc} | Nombre: {data['nombre']} {data['apellido']} | Vínculo: {data['vinculo']}")
    print("-" * 40)

def consultar_funciones_cartelera(asientos_map):
    """Muestra un resumen de la cartelera y la disponibilidad."""
    print("\n--- Consultar Funciones Fin de Semana ---")

    total_funciones = len(CARTELERA)
    peliculas_unicas = set(f['nombre'] for f in CARTELERA)

    print(f"Funciones programadas: {total_funciones}")
    print(f"Películas en cartelera: {len(peliculas_unicas)} ({', '.join(peliculas_unicas)})")
    print("-" * 40)

    for i, f in enumerate(CARTELERA):
        # Calcular asientos disponibles
        mapa = asientos_map.get(i, {})
        disponibles = sum(1 for estado in mapa.values() if estado == 'O')

        print(f"{f['dia']} {f['hora']} - {f['nombre']} | Disponibles: {disponibles}/121")

    print("-" * 40)
