# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15gNmXBoN4DhqRZms911rX-kTXhBHlX0D
"""

# Módulos necesarios
import csv
from data_models import USUARIOS, RESERVAS, CARTELERA
# Importamos solo lo necesario de data_models

def exportar_csv_usuarios():
    """Exporta la lista de usuarios a 'usuarios.csv'."""
    try:
        # Nota: El archivo se crea en la raíz del proyecto, fuera de src/
        with open('../usuarios.csv', 'w', newline='', encoding='utf-8') as file:
            fieldnames = ['documento', 'nombre', 'apellido', 'vinculo', 'valor_tarifa']
            writer = csv.DictWriter(file, fieldnames=fieldnames)

            writer.writeheader()
            for doc, data in USUARIOS.items():
                writer.writerow({
                    'documento': doc,
                    'nombre': data['nombre'],
                    'apellido': data['apellido'],
                    'vinculo': data['vinculo'],
                    'valor_tarifa': data['valor']
                })
        print("\n✅ Usuarios exportados a '../usuarios.csv' con éxito.")
    except Exception as e:
        print(f"\n❌ Error al exportar usuarios: {e}")

def exportar_csv_reservas():
    """Exporta la lista de reservas a 'reservas.csv'."""
    try:
        # Nota: El archivo se crea en la raíz del proyecto, fuera de src/
        with open('../reservas.csv', 'w', newline='', encoding='utf-8') as file:
            fieldnames = ['documento', 'funcion_idx', 'funcion_nombre', 'asiento', 'valor', 'fecha_reserva']
            writer = csv.DictWriter(file, fieldnames=fieldnames)

            writer.writeheader()
            for r in RESERVAS:
                writer.writerow({
                    'documento': r['documento'],
                    'funcion_idx': r['idx_funcion'],
                    'funcion_nombre': CARTELERA[r['idx_funcion']]['nombre'],
                    'asiento': r['asiento'],
                    'valor': r['valor'],
                    'fecha_reserva': r['fecha_reserva']
                })
        print("✅ Reservas exportadas a '../reservas.csv' con éxito.")
    except Exception as e:
        print(f"❌ Error al exportar reservas: {e}")