# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15gNmXBoN4DhqRZms911rX-kTXhBHlX0D
"""

# Módulos necesarios
import random

# --- Estructuras de Datos Globales ---

TARIFAS = {
    1: {"vinculo": "Estudiantes", "valor": 7500},
    2: {"vinculo": "Docentes", "valor": 10000},
    3: {"vinculo": "Administrativos", "valor": 8500},
    4: {"vinculo": "Oficiales internos", "valor": 7000},
    5: {"vinculo": "Público externo", "valor": 15000}
}

CARTELERA = [
    {"dia": "Viernes", "hora": "14:00", "nombre": "Interstellar"},
    {"dia": "Viernes", "hora": "16:00", "nombre": "Interstellar"},
    {"dia": "Viernes", "hora": "18:00", "nombre": "Interstellar"},
    {"dia": "Sábado", "hora": "14:00", "nombre": "Oppenheimer"},
    {"dia": "Sábado", "hora": "16:00", "nombre": "Oppenheimer"},
    {"dia": "Sábado", "hora": "18:00", "nombre": "Oppenheimer"},
    {"dia": "Domingo", "hora": "14:00", "nombre": "The Imitation Game"},
    {"dia": "Domingo", "hora": "16:00", "nombre": "The Imitation Game"},
    {"dia": "Domingo", "hora": "18:00", "nombre": "The Imitation Game"}
]

# Diccionario principal de usuarios: {documento: {datos_usuario}}
USUARIOS = {}

# Lista principal de reservas: [{datos_reserva}]
RESERVAS = []

# Diccionario principal para los mapas de asientos (uno por función)
ASIENTOS = {}

# --- Funciones de Inicialización ---

def crear_mapa_asientos():
    """Crea un mapa de asientos 11x11 con estado 'O' (Disponible)."""
    mapa = {}
    filas = [chr(i) for i in range(ord('A'), ord('K') + 1)] # Filas A a K
    columnas = [str(i) for i in range(1, 12)] # Columnas 1 a 11

    for fila in filas:
        for col in columnas:
            asiento_id = fila + col
            mapa[asiento_id] = 'O'
    return mapa

# Inicializar los mapas de asientos para cada función en la cartelera
for i in range(len(CARTELERA)):
    ASIENTOS[i] = crear_mapa_asientos()

# Simulación de datos iniciales para pruebas (OPCIONAL)
def cargar_datos_simulados():
    global USUARIOS, RESERVAS
    # Crear usuario de prueba
    USUARIOS["123456"] = {"nombre": "Juan", "apellido": "Perez", "vinculo": "Estudiantes", "valor": 7500}
    # Crear reserva de prueba
    RESERVAS.append({
        "documento": "123456",
        "idx_funcion": 0,  # Función 0: Viernes 14:00 Interstellar
        "asiento": "A1",
        "valor": 7500,
        "fecha_reserva": "2025-11-22"
    })
    # Ocupar el asiento A1 para la función 0
    ASIENTOS[0]["A1"] = 'X'

if not USUARIOS:
    cargar_datos_simulados()