# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15gNmXBoN4DhqRZms911rX-kTXhBHlX0D
"""

# Módulos necesarios
import re

def print_errores(errores):
    """Imprime una lista de errores de validación."""
    print("\n[Errores de Validación]:")
    for error in errores:
        print(f" - {error}")
    print("-" * 30)

def validar_nombre(texto):
    """Valida que el nombre/apellido tenga al menos 3 letras y no contenga dígitos."""
    errores = []
    if len(texto) < 3:
        errores.append("Debe tener al menos 3 letras.")
    if re.search(r'\d', texto):
        errores.append("No puede contener números.")
    return errores

def validar_documento(doc):
    """Valida que el documento contenga solo dígitos y tenga entre 3 y 15 caracteres."""
    errores = []
    if not doc.isdigit():
        errores.append("El documento solo debe contener números.")
    if not 3 <= len(doc) <= 15:
        errores.append("El documento debe tener entre 3 y 15 dígitos.")
    return errores